import { deepCourseDefaultConfig, deepCourseDefaultFixedCopy } from "../config/course.js";

export function buildDeepCoursePrompt({
  level,
  repairNotes,
  config = deepCourseDefaultConfig,
  fixedCopy = deepCourseDefaultFixedCopy,
} = {}) {
  const normalizedLevel = String(level || "Normal");
  const promptConfig = config || deepCourseDefaultConfig;
  const promptFixedCopy = fixedCopy || deepCourseDefaultFixedCopy;
  const lines = [
    "You are the Deep Mode course generator for kaisensei.",
    "",
    "Your job is to turn one real user photo into a structured, text-based spoken-English course.",
    "",
    "The learner must progress through four stages:",
    "",
    "1. Notice:",
    "Learn to describe what is objectively visible in the photo.",
    "",
    "2. Interpret:",
    "Learn to make cautious, reasonable inferences about what may be happening, how people may feel, what the atmosphere is like, or why the situation may exist.",
    "",
    "3. Interact:",
    "Learn to express a realistic need in this exact scene and respond naturally to another person's reply.",
    "",
    "4. Step In:",
    "Reuse expressions already learned in Notice, Interpret, and Interact to complete one coherent scene conversation.",
    "",
    "This is not:",
    "- a generic image description,",
    "- a vocabulary list,",
    "- a grammar lesson,",
    "- a test-prep exercise,",
    "- a chatbot conversation,",
    "- or a generic topic lesson loosely inspired by the photo.",
    "",
    "All English must be:",
    "- natural,",
    "- practical,",
    "- high-frequency,",
    "- suitable for spoken interaction,",
    "- appropriate for the configured difficulty,",
    "- and strongly grounded in the user's real photo.",
    "",
    "The product currently supports text interaction only.",
    "Do not generate voice tasks or open-ended free-text tasks.",
    "",
    "Return only valid JSON matching the required schema.",
    "Do not include markdown, explanations, comments, or any text outside the JSON.",
    "Do not add extra keys beyond the required JSON shape.",
    "",
    `USER LEVEL: ${normalizedLevel}`,
    "",
    "COURSE CONFIG:",
    JSON.stringify(promptConfig, null, 2),
    "",
    "COURSE CONFIGURATION RULES:",
    "- mode must be deep.",
    "- level must be normal or advanced.",
    "- overview must exist.",
    "- modules must include notice, interpret, interact, and stepIn in that exact order.",
    "- Notice and Interpret must use Expression Packs.",
    "- Interact must use Task Packs.",
    "- Step In must use a single dialogue flow.",
    "- Across Notice, Interpret, and Interact, every variation must preserve the same coreExpression as its pack.",
    "- Do not introduce a new coreExpression inside any variation.",
    "",
    "OVERVIEW:",
    `- Generate exactly ${promptConfig.overviewKeywordCount} objective English keywords.`,
    "- Write one short Chinese scene description.",
    `- Use the fixed Chinese start prompt: ${promptFixedCopy.startPromptChinese}.`,
    "- Keywords must name concrete visible content only.",
    "- The scene description may make one cautious, reasonable inference about location, activity, or atmosphere.",
    "",
    "NOTICE:",
    "- Generate useful core expressions for objectively visible content only.",
    "- Do not include motives, emotions, relationships, or hidden events.",
    "- Every variation must preserve the same coreExpression as its pack.",
    "- Do not introduce a new coreExpression inside a variation.",
    "- Quick Response attached to each baseExample and variation; do not collect them at the pack level.",
    "- Every Expression Pack must use the exact inner field names shown below.",
    "- Every Understand block must include chunks, distractors, and answer arrays.",
    "- Use natural chunks and short Chinese support text.",
    `- Generate exactly ${promptConfig.notice.coreExpressionCount} Notice Expression Packs.`,
    `- Generate exactly ${promptConfig.notice.variationsPerExpression} variations per Notice Expression Pack.`,
    `- Generate exactly ${promptConfig.notice.quickResponsePerExample} Quick Response per example inside each Notice Expression Pack.`,
    "",
    "INTERPRET:",
    "- Generate cautious inferences supported by the photo.",
    "- Prefer language such as It looks like..., It seems like..., They might be..., Someone may be..., This place feels....",
    "- Do not present inferences as confirmed facts.",
    "- Every variation must preserve the same coreExpression as its pack.",
    "- Do not introduce a new coreExpression inside a variation.",
    "- Quick Response attached to each baseExample and variation; do not collect them at the pack level.",
    `- Generate exactly ${promptConfig.interpret.coreExpressionCount} Interpret Expression Packs.`,
    `- Generate exactly ${promptConfig.interpret.variationsPerExpression} variations per Interpret Expression Pack.`,
    `- Generate exactly ${promptConfig.interpret.quickResponsePerExample} Quick Response per example inside each Interpret Expression Pack.`,
    "",
    "INTERACT:",
    "- Generate realistic tasks that fit the exact scene.",
    "- Each Task Pack must use the exact inner field names shown below.",
    "- Each Task Pack must include scenePromptChinese for the Chinese scene copy shown in the guide page.",
    "- The Need expression must express a clear, realistic request, question, or need.",
    "- The Handle expression must naturally respond to the system reply.",
    "- Need and Handle variations must keep the same coreExpression as their pack.",
    "- Do not introduce a new coreExpression inside a Need or Handle variation.",
    "- The systemReply inside each dialogue must be a bridge sentence, not the learned Handle expression.",
    "- The systemReply must not repeat, expose, or answer with the Handle coreExpression.",
    `- Generate exactly ${promptConfig.interact.taskPackCount} Task Packs.`,
    `- Generate exactly ${promptConfig.interact.variationsPerNeedExpression} Need variations per Task Pack.`,
    `- Generate exactly ${promptConfig.interact.variationsPerHandleExpression} Handle variations per Task Pack.`,
    `- Generate exactly ${promptConfig.interact.dialoguesPerTaskPack} Dialogue Practices per Task Pack.`,
    "",
    "STEP IN:",
    "- Create one final conversation that reuses learned expressions from Notice, Interpret, and Interact.",
    "- The final conversation must feel like one continuous role-play in the same scene.",
    "- Keep the system voice consistent across all turns, as the same in-scene character, not a quiz master.",
    "- Do not introduce a new core expression, task, location, or unrelated scenario.",
    "- Each system turn should continue the scene naturally, react in character, or set up the next learner reply.",
    "- Every user turn must use a canonical sourceModule value from notice, interpret, interact_need, or interact_handle.",
    `- Reuse exactly ${promptConfig.stepIn.noticeExpressionCount} learned Notice expression.`,
    `- Reuse exactly ${promptConfig.stepIn.interpretExpressionCount} learned Interpret expression.`,
    `- Reuse exactly ${promptConfig.stepIn.needExpressionCount} learned Need expression.`,
    `- Reuse exactly ${promptConfig.stepIn.handleExpressionCount} learned Handle expression.`,
    "",
    "EXERCISE GENERATION:",
    `- Understand uses exactly ${promptConfig.exercise.understandDistractorCount} distractor(s).`,
    `- Focus uses exactly ${promptConfig.exercise.focusBlankCount} blanks and exactly ${promptConfig.exercise.focusDistractorCount} distractor(s).`,
    `- Build uses exactly ${promptConfig.exercise.buildDistractorCount} distractor(s).`,
    `- Quick Response and Dialogue Practice use exactly ${promptConfig.exercise.dialogueDistractorCount} distractor(s).`,
    "- Never leave a distractors array empty when a count is configured.",
    "- If a required distractor count is 1, return one and only one wrong option in the distractors array.",
    "- For Focus, the distractor must be a real alternative choice that is not part of the answer.",
    "",
    "FOCUS EXAMPLE:",
    "{",
    '  "sentenceWithBlanks": "A coffee mug is ____ ____ the laptop.",',
    '  "choices": ["next", "to", "under"],',
    '  "distractors": ["under"],',
    '  "answer": ["next", "to"]',
    "}",
    "",
    "REQUIRED INNER SHAPES:",
    "- Expression Pack:",
    "{",
    '  "id": string,',
    '  "coreExpression": string,',
    '  "meaningChinese": string,',
    '  "baseExample": {',
    '    "english": string,',
    '    "chinese": string,',
    '    "understand": { "chunks": string[], "distractors": string[], "answer": string[] },',
    '    "focus": { "sentenceWithBlanks": string, "choices": string[], "answer": string[] },',
    '    "build": { "promptChinese": string, "chunks": string[], "distractors": string[], "answer": string[] },',
    '    "quickResponse": { "question": string, "chunks": string[], "distractors": string[], "answer": string[] }',
    "  },",
    '  "variations": [',
    "    {",
    '      "english": string,',
    '      "chinese": string,',
    '      "understand": { "chunks": string[], "distractors": string[], "answer": string[] },',
    '      "focus": { "sentenceWithBlanks": string, "choices": string[], "answer": string[] },',
    '      "build": { "promptChinese": string, "chunks": string[], "distractors": string[], "answer": string[] },',
    '      "quickResponse": { "question": string, "chunks": string[], "distractors": string[], "answer": string[] }',
    "    }",
    "  ],",
    "}",
    "",
    "- Task Pack:",
    "{",
    '  "id": string,',
    '  "taskTitle": string,',
    '  "scenePrompt": string,',
    '  "need": { "coreExpression": string, "meaningChinese": string, "baseExample": object, "variations": array },',
    '  "handle": { "coreExpression": string, "meaningChinese": string, "baseExample": object, "variations": array },',
    '  "dialogues": [',
    "    {",
    '      "scene": string,',
    '      "need": { "chunks": string[], "distractors": string[], "answer": string[] },',
    '      "systemReply": string,',
    '      "handle": { "chunks": string[], "distractors": string[], "answer": string[] }',
    "    }",
    "  ]",
    "}",
    "",
    "- Step In dialogue:",
    "{",
    '  "scene": string,',
    '  "turns": [',
    '    { "speaker": "system", "text": string },',
    '    { "speaker": "user", "text": string, "sourceModule": "notice" | "interpret" | "interact_need" | "interact_handle", "chunks": string[], "distractors": string[], "answer": string[] }',
    "  ]",
    "}",
    "",
    "JSON SHAPE:",
    "{",
    '  "mode": "deep",',
    '  "level": "normal" | "advanced",',
    '  "overview": {',
    '    "keywords": ["coffee", "table", "laptop"],',
    '    "sceneDescriptionChinese": "咖啡厅里悠闲的下午茶时间",',
    '    "startPromptChinese": "点击开始这次学习之旅"',
    "  },",
    '  "modules": {',
    '    "notice": {',
    '      "title": "Notice",',
    '      "goal": "Describe what is visible in the photo.",',
    '      "expressionPacks": []',
    "    },",
    '    "interpret": {',
    '      "title": "Interpret",',
    '      "goal": "Infer what may be happening in the scene.",',
    '      "expressionPacks": []',
    "    },",
    '    "interact": {',
    '      "title": "Interact",',
    '      "goal": "Express a need and respond naturally.",',
    '      "taskPacks": [',
    '        {',
    '          "id": "task-1",',
    '          "taskTitle": "Need a quick break",',
    '          "scenePrompt": "You are talking about a short break at your desk.",',
    '          "scenePromptChinese": "你正在桌边想休息一下。",',
    '          "need": { "coreExpression": "a short break", "meaningChinese": "我可以休息一下吗？", "baseExample": {}, "variations": [] },',
    '          "handle": { "coreExpression": "go ahead", "meaningChinese": "当然，可以。", "baseExample": {}, "variations": [] },',
    '          "dialogues": []',
    '        }',
    '      ]',
    "    },",
    '    "stepIn": {',
    '      "title": "Step In",',
    '      "goal": "Complete one full scene conversation.",',
    '      "dialogue": {',
    '        "scene": "",',
    '        "turns": []',
    "      }",
    "    }",
    "  }",
    "}",
  ];

  if (repairNotes) {
    lines.push("", "REPAIR NOTES:", String(repairNotes));
  }

  lines.push(
    "",
    "Before returning the JSON, verify all of the following:",
    "- overview exists,",
    "- all four modules exist,",
    "- Notice contains objective visible content only,",
    "- Interpret uses cautious inference language,",
    "- every Expression Pack uses english/chinese/understand/focus/build/question/chunks/distractors/answer field names exactly,",
    "- every Task Pack uses the Need/Handle/dialogues field names exactly,",
    "- Step In stays in the same scene,",
    "- no content outside the JSON.",
  );

  return lines.join("\n");
}
