export function buildDeepCoursePrompt({ level, repairNotes } = {}) {
  const normalizedLevel = String(level || "Normal");
  const lines = [
    "You are the Deep Mode course generator for kaisensei.",
    "",
    "Your job is to turn one real user photo into a structured, text-based spoken-English course.",
    "",
    "The learner must progress through four stages:",
    "",
    "1. Notice:",
    "Learn to describe what is objectively visible in the photo.",
    "",
    "2. Interpret:",
    "Learn to make cautious, reasonable inferences about what may be happening, how people may feel, what the atmosphere is like, or why the situation may exist.",
    "",
    "3. Interact:",
    "Learn to express a realistic need in this exact scene and respond naturally to another person's reply.",
    "",
    "4. Step In:",
    "Reuse expressions already learned in Notice, Interpret, and Interact to complete one coherent scene conversation.",
    "",
    "This is not:",
    "- a generic image description,",
    "- a vocabulary list,",
    "- a grammar lesson,",
    "- a test-prep exercise,",
    "- a chatbot conversation,",
    "- or a generic topic lesson loosely inspired by the photo.",
    "",
    "All English must be:",
    "- natural,",
    "- practical,",
    "- high-frequency,",
    "- suitable for spoken interaction,",
    "- appropriate for the configured difficulty,",
    "- and strongly grounded in the user's real photo.",
    "",
    "The product currently supports text interaction only.",
    "Do not generate voice tasks or open-ended free-text tasks.",
    "",
    "Return only valid JSON matching the required schema.",
    "Do not include markdown, explanations, comments, or any text outside the JSON.",
    "Do not add extra keys beyond the required JSON shape.",
    "",
    `USER LEVEL: ${normalizedLevel}`,
    "",
    "COURSE CONFIGURATION RULES:",
    "- mode must be deep.",
    "- level must be normal or advanced.",
    "- overview must exist.",
    "- modules must include notice, interpret, interact, and stepIn in that exact order.",
    "- Notice and Interpret must use Expression Packs.",
    "- Interact must use Task Packs.",
    "- Step In must use a single dialogue flow.",
    "",
    "OVERVIEW:",
    "- Generate exactly 3 objective English keywords.",
    "- Write one short Chinese scene description.",
    "- Use the fixed Chinese start prompt from the product.",
    "- Keywords must name concrete visible content only.",
    "- The scene description may make one cautious, reasonable inference about location, activity, or atmosphere.",
    "",
    "NOTICE:",
    "- Generate useful core expressions for objectively visible content only.",
    "- Do not include motives, emotions, relationships, or hidden events.",
    "- Every Expression Pack must use the exact inner field names shown below.",
    "- Every Understand block must include chunks, distractors, and answer arrays.",
    "- Use natural chunks and short Chinese support text.",
    "",
    "INTERPRET:",
    "- Generate cautious inferences supported by the photo.",
    "- Prefer language such as It looks like..., It seems like..., They might be..., Someone may be..., This place feels....",
    "- Do not present inferences as confirmed facts.",
    "",
    "INTERACT:",
    "- Generate realistic tasks that fit the exact scene.",
    "- Each Task Pack must use the exact inner field names shown below.",
    "- The Need expression must express a clear, realistic request, question, or need.",
    "- The Handle expression must naturally respond to the system reply.",
    "",
    "STEP IN:",
    "- Create one final conversation that reuses learned expressions from Notice, Interpret, and Interact.",
    "- Do not introduce a new core expression, task, location, or unrelated scenario.",
    "- The final conversation must form one coherent situation.",
    "",
    "REQUIRED INNER SHAPES:",
    "- Expression Pack:",
    "{",
    '  "id": string,',
    '  "coreExpression": string,',
    '  "meaningChinese": string,',
    '  "baseExample": {',
    '    "english": string,',
    '    "chinese": string,',
    '    "understand": { "chunks": string[], "distractors": string[], "answer": string[] },',
    '    "focus": { "sentenceWithBlanks": string, "choices": string[], "answer": string[] },',
    '    "build": { "promptChinese": string, "chunks": string[], "distractors": string[], "answer": string[] }',
    "  },",
    '  "variations": [',
    "    {",
    '      "english": string,',
    '      "chinese": string,',
    '      "understand": { "chunks": string[], "distractors": string[], "answer": string[] },',
    '      "focus": { "sentenceWithBlanks": string, "choices": string[], "answer": string[] },',
    '      "build": { "promptChinese": string, "chunks": string[], "distractors": string[], "answer": string[] }',
    "    }",
    "  ],",
    '  "quickResponses": [',
    "    {",
    '      "question": string,',
    '      "chunks": string[],',
    '      "distractors": string[],',
    '      "answer": string[]',
    "    }",
    "  ]",
    "}",
    "",
    "- Task Pack:",
    "{",
    '  "id": string,',
    '  "taskTitle": string,',
    '  "scenePrompt": string,',
    '  "need": { "coreExpression": string, "meaningChinese": string, "baseExample": object, "variations": array },',
    '  "handle": { "coreExpression": string, "meaningChinese": string, "baseExample": object, "variations": array },',
    '  "dialogues": [',
    "    {",
    '      "scene": string,',
    '      "need": { "chunks": string[], "distractors": string[], "answer": string[] },',
    '      "systemReply": string,',
    '      "handle": { "chunks": string[], "distractors": string[], "answer": string[] }',
    "    }",
    "  ]",
    "}",
    "",
    "- Step In dialogue:",
    "{",
    '  "scene": string,',
    '  "turns": [',
    '    { "speaker": "system", "text": string },',
    '    { "speaker": "user", "text": string, "sourceModule": string, "chunks": string[], "distractors": string[], "answer": string[] }',
    "  ]",
    "}",
    "",
    "JSON SHAPE:",
    "{",
    '  "mode": "deep",',
    '  "level": "normal" | "advanced",',
    '  "overview": {',
    '    "keywords": ["coffee", "table", "laptop"],',
    '    "sceneDescriptionChinese": "咖啡厅里悠闲的下午茶时间",',
    '    "startPromptChinese": "点击开始这次学习之旅"',
    "  },",
    '  "modules": {',
    '    "notice": {',
    '      "title": "Notice",',
    '      "goal": "Describe what is visible in the photo.",',
    '      "expressionPacks": []',
    "    },",
    '    "interpret": {',
    '      "title": "Interpret",',
    '      "goal": "Infer what may be happening in the scene.",',
    '      "expressionPacks": []',
    "    },",
    '    "interact": {',
    '      "title": "Interact",',
    '      "goal": "Express a need and respond naturally.",',
    '      "taskPacks": []',
    "    },",
    '    "stepIn": {',
    '      "title": "Step In",',
    '      "goal": "Complete one full scene conversation.",',
    '      "dialogue": {}',
    "    }",
    "  }",
    "}",
  ];

  if (repairNotes) {
    lines.push("", "REPAIR NOTES:", String(repairNotes));
  }

  lines.push(
    "",
    "Before returning the JSON, verify all of the following:",
    "- overview exists,",
    "- all four modules exist,",
    "- Notice contains objective visible content only,",
    "- Interpret uses cautious inference language,",
    "- every Expression Pack uses english/chinese/understand/focus/build/question/chunks/distractors/answer field names exactly,",
    "- every Task Pack uses the Need/Handle/dialogues field names exactly,",
    "- Step In stays in the same scene,",
    "- no content outside the JSON.",
  );

  return lines.join("\n");
}
