export const DEEP_COPY = {
  loading: [
    {
      primary: "Reading the scene...",
      secondary: "正在读取场景...",
    },
    {
      primary: "Building your practice...",
      secondary: "正在生成练习内容...",
    },
    {
      primary: "Preparing your challenge...",
      secondary: "正在准备挑战...",
    },
  ],
  loadingStages: [
    {
      title: "Reading the scene",
      description: "Finding visible objects and the main setup.",
    },
    {
      title: "Building your practice",
      description: "Shaping Notice and Interpret exercises.",
    },
    {
      title: "Preparing your challenge",
      description: "Setting up Interact and Step In.",
    },
  ],
  nextStageWaiting: "正在生成下一阶段",
  overviewPrompt: "Ready to explore this scene?",
  overviewTitle: "Overview",
  overviewModeLabel: "Deep Mode",
  startPractice: "Start Practice",
  startDeepMode: "Start Deep Mode →",
  backConfirm: "退出这节深度课程吗？返回后可以重新拍照并切换模式。",
  retry: "The lesson got lost on the way.",
  retryAction: "Try again",
  errorTitle: "The lesson got lost on the way.",
  errorBody: "Try again from the camera screen.",
  errorChinese: "课程在路上丢了，请回到拍照页再试一次。",
  summaryContinue: "Continue to course recap →",
  completionTitle: "Great job!",
  completionDescription: "You've completed the Deep Mode course.",
  completionChinese: "你已完成 Deep Mode 课程！",
  completionReplayTitle: "对话回顾",
  stepInGuideGoal: "综合之前所学，完成一段完整的场景对话",
  interactSummary: "You can now ask for what you need and respond naturally.",
  stepInSummary: "You can finish the full scene conversation.",
  dialogueNeedPrompt: "先说你的需要",
  dialogueHandlePrompt: "自然接一句",
  sceneLabel: "场景",
  buildYourAnswer: "把答案拼出来",
  buildYourAnswerChinese: "在这里拼出答案",
  playAudio: "Play audio",
  reorderInstruction: "把词块排一排，读懂这句话",
  interactReorderInstruction: "把词块排一排",
  focusInstruction: "用下面的词块把句子补完整",
  buildInstruction: "把这句话拼出来",
  noticeQuickResponseChinese: "这句话主要在说什么",
  interpretQuickResponseChinese: "画面里大概在发生什么",
  completedNoticeTitle: "你学到的核心表达",
  completedInterpretTitle: "你总结出的核心表达",
  needExpressionsTitle: "需要表达",
  handleExpressionsTitle: "回应表达",
  capabilitySummaryTitle: "能力小结",
  tapChunksToBuild: "点选词块，拼出你的答案",
  tapChunksThenCheck: "点选词块，再检查答案",
  tapChunksThenSend: "点选词块，再发送答案",
  continueToInterpret: "Continue to Interpret →",
  continueToInteract: "Continue to Interact →",
  continueToStepIn: "Continue to Step In →",
  backToCamera: "Back to camera",
  repeatPractice: "Practice again",
  reset: "Reset",
  hint: "Hint",
  check: "Check",
  send: "Send",
  continue: "Continue",
  finishAction: "Finish",
  correct: "Nice. This sentence is yours now.",
  incorrect: "Almost. Try again.",
  challengeTitle: "任务",
  challengePrompt: "留在场景里，把对话接下去",
  challengePromptChinese: "留在场景里，把对话接下去",
  dialogueTaskPrompt: "遇到上面的场景，你会怎么说？",
  dialogueTaskClosePrompt: "好极了！给对话结个尾吧",
};
