export const DEEP_COPY = {
  loading: [
    {
      primary: "Reading the scene...",
      secondary: "正在读取场景...",
    },
    {
      primary: "Building your practice...",
      secondary: "正在生成练习内容...",
    },
    {
      primary: "Preparing your challenge...",
      secondary: "正在准备挑战...",
    },
  ],
  loadingStages: [
    {
      title: "Reading the scene",
      description: "Finding visible objects and the main setup.",
    },
    {
      title: "Building your practice",
      description: "Shaping Notice and Interpret exercises.",
    },
    {
      title: "Preparing your challenge",
      description: "Setting up Interact and Step In.",
    },
  ],
  overviewPrompt: "Ready to explore this scene?",
  startPractice: "Start Practice",
  startDeepMode: "Start Deep Mode →",
  backConfirm: "退出这节深度课程吗？返回后可以重新拍照并切换模式。",
  retry: "The lesson got lost on the way.",
  completionTitle: "Great job!",
  completionDescription: "You've completed the Deep Mode course.",
  completionChinese: "你已完成 Deep Mode 课程！",
  interactSummary: "You can now ask for what you need and respond naturally.",
  stepInSummary: "You can finish the full scene conversation.",
  dialogueNeedPrompt: "Your turn: Build your Need",
  dialogueHandlePrompt: "Your turn: Build your Handle",
  dialogueNeedOpening: "A coworker starts the conversation.",
  tapChunksToBuild: "Tap chunks to build your answer.",
  tapChunksThenCheck: "Tap chunks, then check your answer.",
  tapChunksThenSend: "Tap chunks, then send your answer.",
  continueToInterpret: "Continue to Interpret →",
  continueToInteract: "Continue to Interact →",
  continueToStepIn: "Continue to Step In →",
  backToCamera: "Back to camera",
  repeatPractice: "Practice again",
  reset: "Reset",
  hint: "Hint",
  check: "Check",
  send: "Send",
  continue: "Continue",
  finishAction: "Finish",
  correct: "Nice. This sentence is yours now.",
  incorrect: "Almost. Try again.",
  challengeTitle: "Challenge",
  challengePrompt: "Use what you've learned!",
  challengePromptChinese: "请使用你学到的内容！",
};
